FROM node:20-alpine AS base

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

ARG NEXT_PUBLIC_ZYNEX_API_URL=http://localhost:4101
ARG NEXTAUTH_URL=http://localhost:3000
ARG NEXTAUTH_SECRET=zynex-local-nextauth-secret

ENV NEXT_PUBLIC_ZYNEX_API_URL=$NEXT_PUBLIC_ZYNEX_API_URL
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json tsconfig.base.json ./
COPY apps/web ./apps/web
COPY packages ./packages

RUN pnpm install --frozen-lockfile
RUN pnpm --filter web build

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000

CMD ["pnpm", "--filter", "web", "exec", "next", "start", "-p", "3000"]
