{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zynex-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "zynex.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  serviceName: zynex-redis
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zynex
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zynex
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.port }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: zynex-redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "zynex.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zynex
    app.kubernetes.io/component: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: redis
{{- end }}
