{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: zynex-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "zynex.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | quote }}
  ZYNEX_JWT_SECRET: {{ .Values.secrets.ZYNEX_JWT_SECRET | quote }}
  NEXTAUTH_SECRET: {{ .Values.secrets.NEXTAUTH_SECRET | quote }}
  GROQ_API_KEY: {{ .Values.secrets.GROQ_API_KEY | quote }}
  OPENROUTER_API_KEY: {{ .Values.secrets.OPENROUTER_API_KEY | quote }}
  OPENAI_API_KEY: {{ .Values.secrets.OPENAI_API_KEY | quote }}
  RESEND_API_KEY: {{ .Values.secrets.RESEND_API_KEY | quote }}
  SPACESHIP_SMTP_HOST: {{ .Values.secrets.SPACESHIP_SMTP_HOST | quote }}
  SPACESHIP_SMTP_USER: {{ .Values.secrets.SPACESHIP_SMTP_USER | quote }}
  SPACESHIP_SMTP_PASS: {{ .Values.secrets.SPACESHIP_SMTP_PASS | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.TWILIO_ACCOUNT_SID | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.TWILIO_AUTH_TOKEN | quote }}
  TWILIO_FROM_PHONE: {{ .Values.secrets.TWILIO_FROM_PHONE | quote }}
{{- end }}
